### ISSUE TITLE
The process of graph prompt tuning for node-wise tasks

### ISSUE THREAD

**Issue by hzjsxu** [LuckyTiger123/GPF#1]
Hi,

A wonderful work. Could you share codes regarding the process of graph prompt tuning for node-wise tasks in this paper? I'd like to test its effectiveness on my data. 

Thanks!

![image](https://github.com/LuckyTiger123/GPF/assets/45815139/b9449f83-d0a1-4154-9682-9b1164b449cb)

**Comment by LuckyTiger123** [comment]
Our method has no constraints on the specific form of subgraph GNNs, and you are free to choose any subgraph GNNs as backbone models. The code in the related works “GraphPrompt: Unifying Pre-Training and Downstream Tasks for Graph Neural Networks”(https://github.com/Starlien95/GraphPrompt) and "All in One: Multi-task Prompting for Graph Neural Networks"(https://github.com/sheldonresearch/ProG) provide reference versions of subgraph GNNs that can be borrowed from. You can refer to these repositories to conduct node-wise tasks.

**Comment by hzjsxu** [comment]
> Our method has no constraints on the specific form of subgraph GNNs, and you are free to choose any subgraph GNNs as backbone models. The code in the related works “GraphPrompt: Unifying Pre-Training and Downstream Tasks for Graph Neural Networks”(https://github.com/Starlien95/GraphPrompt) and "All in One: Multi-task Prompting for Graph Neural Networks"(https://github.com/sheldonresearch/ProG) provide reference versions of subgraph GNNs that can be borrowed from. You can refer to these repositories to conduct node-wise tasks.

Thanks. I got it.
