### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by Fredalively** [LuckyTiger123/GPF#2]
may I ask what dataset it is? bio and che, and how to solve the problem "RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again" when  I reproduce.

**Comment by LuckyTiger123** [comment]
Hello! Your issue stems from the fact that the dataset itself uses an older version of PyG, while your environment has a newer version of PyG. Please strictly adhere to the environment configuration we provide to set up the experimental environment (PyG 1.0.3).
