### ISSUE TITLE
What is the meaning of 9 in edge features mapping to embedding? 

### ISSUE THREAD

**Issue by WeigangLu** [LuckyTiger123/GPF#3]
Could you please tell me why you fixed the edge feature dimension at 9? I encountered an issue with contacting the edge attr with self_loop_attr.

**Comment by LuckyTiger123** [comment]
Hello! We guess that your issue arises when using the model under the "bio" category. The fixed edge feature of 9 is an inherent property of the protein network dataset, a setting not proposed by us, but rather provided by the dataset provider (please refer to the dataset release code at https://github.com/snap-stanford/pretrain-gnns). Under normal circumstances, there should be no issues with running the code. Please strictly follow the environment configuration we provide to set up the experimental environment. It is worth mentioning that the PyG version used by this dataset is quite low, and using a higher version of PyG recklessly will lead to a series of errors.
